name: SimpleAPI
main: simple.brainsynder.Core
authors: ["brainsynder"]
version: ${project.version}
loadbefore: [SimplePets, SimpleArmorStandEdit, SimpleMobs, SimpleGadgets-Addon, CSkulls, AntiHackedPotions, SimpleGadgets, SimpleParticles]
load: STARTUP
api-version: 1.13
commands:
  particlemaker:
    description: Sends particles to the players location.
  action:
    description: Send a message above the hotbar.
  tab:
    description: Set the tab header & footer.
  titlemaker:
    description: Send a title message to player(s).
  simpleapi:
    description: Used to check for updates.
  userhistory:
    description: Get a players past or current name(s).