name: SimpleAPI
main: simple.brainsynder.Core
authors: ["brainsynder"]
version: 3.8
loadbefore: [SimplePets, SimpleArmorStandEdit, SimpleMobs, SimpleGadgets-Addon, CSkulls, AntiHackedPotions, SimpleGadgets, SimpleParticles]
load: STARTUP
commands:
  action:
    description: Send a message above the hotbar.
  tab:
    description: Set the tab header & footer.
  titlemaker:
    description: Send a title message to player(s).
  simpleapi:
    description: Used to check for updates.
  compass:
    description: Set the location of the compass needle.
  armorcolor:
    description: Give yourself armor with colors from RGB values.
  firework:
    description: Launch a random firework in the air.
  itemrename:
    description: Rename an item with ease and color codes!
  userhistory:
    description: Get a players past or current name(s).